name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

version-resolver:
    major:
        labels:
            - 'breaking'
            - 'breaking-change'
    minor:
        labels:
            - 'feature'
            - 'enhancement'
    patch:
        labels:
            - 'bug'
            - 'fix'
            - 'docs'
            - 'dependencies'
            - 'chore'
    default: patch

categories:
    - title: '🚨 Breaking Changes'
      labels:
          - 'breaking'
          - 'breaking-change'
    - title: '🎉 New Features'
      labels:
          - 'feature'
          - 'enhancement'
    - title: '🐛 Bug Fixes'
      labels:
          - 'bug'
          - 'fix'
    - title: '📚 Documentation'
      labels:
          - 'docs'
      collapse-after: 3
    - title: '🧰 Maintenance'
      labels:
          - 'chore'
          - 'ci'
      collapse-after: 3
    - title: '⬆️ Dependencies'
      label: 'dependencies'
      collapse-after: 3

exclude-labels:
    - 'skip-changelog'

autolabeler:
    - label: 'docs'
      files:
          - '*.md'
          - 'docs/**'
    - label: 'bug'
      branch:
          - '/fix\/.+/'
    - label: 'feature'
      branch:
          - '/feature\/.+/'
    - label: 'dependencies'
      files:
          - 'package*.json'
          - 'composer*.json'
    - label: 'ci'
      files:
          - '.github/**'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

template: |
    ## What's Changed

    $CHANGES

    ## Installation

    ### Composer
    ```bash
    composer require pikari-inc/pikari-image-grid-block:$RESOLVED_VERSION
    ```

    ### WordPress Plugin
    Download `pikari-image-grid-block.zip` from the assets below.

    **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
